// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tracker.Data;

#nullable disable

namespace Tracker.Data.Migrations
{
    [DbContext(typeof(TrackerDbContext))]
    [Migration("20260608150041_AddPortMapping")]
    partial class AddPortMapping
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tracker.Data.Entities.Language", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extensions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "C",
                            Extensions = ".c,.h",
                            Name = "c"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "C#",
                            Extensions = ".cs",
                            Name = "csharp"
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Java",
                            Extensions = ".java",
                            Name = "java"
                        });
                });

            modelBuilder.Entity("Tracker.Data.Entities.Method", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BodyEndColumn")
                        .HasColumnType("int");

                    b.Property<int>("BodyEndLine")
                        .HasColumnType("int");

                    b.Property<int>("BodyStartColumn")
                        .HasColumnType("int");

                    b.Property<int>("BodyStartLine")
                        .HasColumnType("int");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EndColumn")
                        .HasColumnType("int");

                    b.Property<int>("EndLine")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PortedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortedPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReturnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartColumn")
                        .HasColumnType("int");

                    b.Property<int>("StartLine")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StatusComment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("CurrentName");

                    b.HasIndex("Status");

                    b.HasIndex("FileId", "OriginalName")
                        .IsUnique()
                        .HasFilter("[RemovedAt] IS NULL");

                    b.ToTable("Methods");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MethodCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CallColumn")
                        .HasColumnType("int");

                    b.Property<int>("CallLine")
                        .HasColumnType("int");

                    b.Property<int?>("CalleeMethodId")
                        .HasColumnType("int");

                    b.Property<int>("CallerMethodId")
                        .HasColumnType("int");

                    b.Property<string>("RawCalleeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalleeMethodId");

                    b.HasIndex("CallerMethodId");

                    b.ToTable("MethodCalls");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MethodParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EndColumn")
                        .HasColumnType("int");

                    b.Property<int>("EndLine")
                        .HasColumnType("int");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartColumn")
                        .HasColumnType("int");

                    b.Property<int>("StartLine")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.ToTable("MethodParameters");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Milestone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Milestones");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MilestoneMethod", b =>
                {
                    b.Property<int>("MilestoneId")
                        .HasColumnType("int");

                    b.Property<int>("MethodId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("MilestoneId", "MethodId");

                    b.HasIndex("MethodId");

                    b.ToTable("MilestoneMethods");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RootPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tracker.Data.Entities.RenameHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MethodId")
                        .HasColumnType("int");

                    b.Property<string>("NewFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NewStartColumn")
                        .HasColumnType("int");

                    b.Property<int?>("NewStartLine")
                        .HasColumnType("int");

                    b.Property<string>("OldFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OldStartColumn")
                        .HasColumnType("int");

                    b.Property<int?>("OldStartLine")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.ToTable("RenameHistories");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndColumn")
                        .HasColumnType("int");

                    b.Property<int>("EndLine")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartColumn")
                        .HasColumnType("int");

                    b.Property<int>("StartLine")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FileId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "RelativePath")
                        .IsUnique()
                        .HasFilter("[RemovedAt] IS NULL");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Method", b =>
                {
                    b.HasOne("Tracker.Data.Entities.TrackedClass", "Class")
                        .WithMany("Methods")
                        .HasForeignKey("ClassId");

                    b.HasOne("Tracker.Data.Entities.TrackedFile", "File")
                        .WithMany("Methods")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("File");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MethodCall", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Method", "CalleeMethod")
                        .WithMany("CallsAsCallee")
                        .HasForeignKey("CalleeMethodId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tracker.Data.Entities.Method", "CallerMethod")
                        .WithMany("CallsAsCaller")
                        .HasForeignKey("CallerMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalleeMethod");

                    b.Navigation("CallerMethod");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MethodParameter", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Method", "Method")
                        .WithMany("Parameters")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Milestone", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Milestone", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Tracker.Data.Entities.Project", "Project")
                        .WithMany("Milestones")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tracker.Data.Entities.MilestoneMethod", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Method", "Method")
                        .WithMany("MilestoneMethods")
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tracker.Data.Entities.Milestone", "Milestone")
                        .WithMany("MilestoneMethods")
                        .HasForeignKey("MilestoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Method");

                    b.Navigation("Milestone");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Project", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Language", "Language")
                        .WithMany("Projects")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");
                });

            modelBuilder.Entity("Tracker.Data.Entities.RenameHistory", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Method", "Method")
                        .WithMany("RenameHistories")
                        .HasForeignKey("MethodId");

                    b.Navigation("Method");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedClass", b =>
                {
                    b.HasOne("Tracker.Data.Entities.TrackedFile", "File")
                        .WithMany("Classes")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedFile", b =>
                {
                    b.HasOne("Tracker.Data.Entities.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Language", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Method", b =>
                {
                    b.Navigation("CallsAsCallee");

                    b.Navigation("CallsAsCaller");

                    b.Navigation("MilestoneMethods");

                    b.Navigation("Parameters");

                    b.Navigation("RenameHistories");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Milestone", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MilestoneMethods");
                });

            modelBuilder.Entity("Tracker.Data.Entities.Project", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Milestones");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedClass", b =>
                {
                    b.Navigation("Methods");
                });

            modelBuilder.Entity("Tracker.Data.Entities.TrackedFile", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Methods");
                });
#pragma warning restore 612, 618
        }
    }
}
